@if(linux)

package tomei

// pwru: eBPF packet tracer (linux only)
pwru: {
	apiVersion: "tomei.terassyi.net/v1beta1"
	kind:       "Tool"
	metadata: name: "pwru"
	spec: {
		installerRef: "aqua"
		version:      "v1.0.11"
		source: {
			url:         "https://github.com/cilium/pwru/releases/download/v1.0.11/pwru-linux-\(_arch).tar.gz"
			archiveType: "tar.gz"
		}
	}
}

// apt SystemInstaller: wires tomei's built-in APT backend (Debian/Ubuntu).
// Requires `tomei apply --system`. spec.commands are descriptive metadata —
// the backend owns the actual apt-get/dpkg invocation.
apt: {
	apiVersion: "tomei.terassyi.net/v1beta1"
	kind:       "SystemInstaller"
	metadata: name: "apt"
	spec: {
		pattern:    "delegation"
		privileged: true
		commands: {
			install: {command: "sudo apt-get install -y"}
			remove: {command: "sudo apt-get remove -y"}
			check: {command: "dpkg -s"}
		}
	}
}

// System packages installed via apt under `tomei apply --system`, split by
// purpose. Generic build tooling is kept separate from the per-language sets.

// base: minimal user-facing OS packages (formerly the ubuntu.txt bootstrap
// script). fish is the login shell, neovim the editor, file a common CLI dep,
// locales provides en_US.UTF-8 (generated by run_once_after_92-locale).
// NOT here, because they must exist BEFORE `chezmoi apply` (this SystemPackageSet
// is applied by run_onchange_after_01-apply-tomei, i.e. *after* files):
//   - curl/ca-certificates/sudo/git: prerequisites for installing tomei itself;
//   - jq: used by dot_config/zed/modify_settings.json.tmpl during file apply.
// Those are provided by the base image (Dockerfile) / manual Phase 0 instead.
// (Runtime jq also comes from the aqua cliTools set.)
base: {
	apiVersion: "tomei.terassyi.net/v1beta1"
	kind:       "SystemPackageSet"
	metadata: name: "base"
	spec: {
		installerRef: "apt"
		packages: ["fish", "neovim", "file", "locales"]
	}
}

// common-build: general build toolchain shared across languages.
// mold is a fast linker (ELF/Linux only) usable by gcc/clang for C/C++/Rust.
commonBuild: {
	apiVersion: "tomei.terassyi.net/v1beta1"
	kind:       "SystemPackageSet"
	metadata: name: "common-build"
	spec: {
		installerRef: "apt"
		packages: ["build-essential", "pkg-config", "cmake", "mold"]
	}
}

// bpf-dev: eBPF compilation (clang/llvm), libbpf/CO-RE, bpftool, perf.
// bpftool is the standalone package (kernel-independent), preferred over the
// linux-tools-generic copy which is tied to the running kernel version.
// linux-tools-generic is kept for perf. libclang-dev provides libclang for
// bindgen (used by rust+aya's aya-tool to generate kernel bindings).
bpfDev: {
	apiVersion: "tomei.terassyi.net/v1beta1"
	kind:       "SystemPackageSet"
	metadata: name: "bpf-dev"
	spec: {
		installerRef: "apt"
		packages: [
			"clang",
			"llvm",
			"libbpf-dev",
			"libelf-dev",
			"libclang-dev",
			"bpftool",
			"linux-headers-generic",
			"linux-tools-generic",
		]
	}
}

// rust-dev: Rust-specific system deps (openssl crate).
rustDev: {
	apiVersion: "tomei.terassyi.net/v1beta1"
	kind:       "SystemPackageSet"
	metadata: name: "rust-dev"
	spec: {
		installerRef: "apt"
		packages: ["libssl-dev"]
	}
}

// lua-build: deps for the lua runtime's source build (readline).
luaBuild: {
	apiVersion: "tomei.terassyi.net/v1beta1"
	kind:       "SystemPackageSet"
	metadata: name: "lua-build"
	spec: {
		installerRef: "apt"
		packages: ["libreadline-dev"]
	}
}

// media: media tooling (ffmpeg) via apt.
media: {
	apiVersion: "tomei.terassyi.net/v1beta1"
	kind:       "SystemPackageSet"
	metadata: name: "media"
	spec: {
		installerRef: "apt"
		packages: ["ffmpeg"]
	}
}
