@if(linux)

package tomei

// pwru: eBPF packet tracer (linux only)
pwru: {
	apiVersion: "tomei.terassyi.net/v1beta1"
	kind:       "Tool"
	metadata: name: "pwru"
	spec: {
		installerRef: "aqua"
		version:      "v1.0.11"
		source: {
			url:         "https://github.com/cilium/pwru/releases/download/v1.0.11/pwru-linux-\(_arch).tar.gz"
			archiveType: "tar.gz"
		}
	}
}

// k3s: Lightweight Kubernetes (linux only — upstream ships no darwin build,
// the release assets are Linux binaries)
k3s: {
	apiVersion: "tomei.terassyi.net/v1beta1"
	kind:       "Tool"
	metadata: {
		name:        "k3s"
		description: "Lightweight Kubernetes"
	}
	spec: {
		version:    "v1.36.2+k3s1"
		privileged: true
		commands: {
			install: [
				"sudo curl -fsSL https://github.com/k3s-io/k3s/releases/download/\(spec.version)/k3s\(_k3sArchMap[_arch]) -o /usr/local/bin/k3s",
				"sudo chmod +x /usr/local/bin/k3s",
			]
			check: ["k3s --version"]
			remove: ["sudo rm -f /usr/local/bin/k3s"]
		}
	}
	// amd64 is the unsuffixed asset (k3s); other arches carry a suffix (k3s-arm64).
	_k3sArchMap: {amd64: "", arm64: "-arm64"}
}

// firecracker: lightweight VMM for serverless workloads (linux only).
// Assets are named firecracker-<ver>-<uname arch>; the tarball holds
// firecracker-<ver>-<arch> and jailer-<ver>-<arch>, renamed on extraction.
firecracker: {
	apiVersion: "tomei.terassyi.net/v1beta1"
	kind:       "Tool"
	metadata: {
		name:        "firecracker"
		description: "Lightweight Virtual Machine Monitor"
	}
	spec: {
		let _suffix = "\(spec.version)-\(_unameArchMap[_arch])"

		version:    "v1.16.1"
		privileged: true
		commands: {
			install: [
				"curl -fsSL https://github.com/firecracker-microvm/firecracker/releases/download/\(spec.version)/firecracker-\(_suffix).tgz | sudo tar -xz -C /usr/local/bin --strip-components=1 --transform=\"s/firecracker-\(_suffix)$/firecracker/\" --transform=\"s/jailer-\(_suffix)$/jailer/\" --wildcards \"*/firecracker-\(_suffix)\" \"*/jailer-\(_suffix)\"",
			]
			check: ["firecracker --version"]
			remove: ["sudo rm -f /usr/local/bin/firecracker /usr/local/bin/jailer"]
		}
	}
}

// kata-containers: secure container runtime with lightweight VMs (linux only)
kataContainers: {
	apiVersion: "tomei.terassyi.net/v1beta1"
	kind:       "Tool"
	metadata: {
		name:        "kata-containers"
		description: "Secure container runtime using lightweight virtual machines"
	}
	spec: {
		version:    "4.0.0"
		privileged: true
		commands: {
			install: [
				"curl -fsSL https://github.com/kata-containers/kata-containers/releases/download/\(spec.version)/kata-static-\(spec.version)-\(_arch).tar.zst | sudo tar -I zstd -x -C /",
				"sudo ln -sf /opt/kata/bin/kata-runtime /usr/local/bin/kata-runtime",
				"sudo ln -sf /opt/kata/bin/containerd-shim-kata-v2 /usr/local/bin/containerd-shim-kata-v2",
			]
			check: ["kata-runtime --version"]
			remove: [
				"sudo rm -f /usr/local/bin/kata-runtime /usr/local/bin/containerd-shim-kata-v2",
				"sudo rm -rf /opt/kata",
			]
		}
	}
}

// apt SystemInstaller: wires tomei's built-in APT backend (Debian/Ubuntu).
// Requires `tomei apply --system`. spec.commands are descriptive metadata —
// the backend owns the actual apt-get/dpkg invocation.
apt: {
	apiVersion: "tomei.terassyi.net/v1beta1"
	kind:       "SystemInstaller"
	metadata: name: "apt"
	spec: {
		pattern:    "delegation"
		privileged: true
		commands: {
			install: {command: "sudo apt-get install -y"}
			remove: {command: "sudo apt-get remove -y"}
			check: {command: "dpkg -s"}
		}
	}
}

// System packages installed via apt under `tomei apply --system`, split by
// purpose. Generic build tooling is kept separate from the per-language sets.

// base: minimal user-facing OS packages (formerly the ubuntu.txt bootstrap
// script). fish is the login shell, neovim the editor, file a common CLI dep,
// locales provides en_US.UTF-8 (generated by run_once_after_92-locale).
// NOT here, because they must exist BEFORE `chezmoi apply` (this SystemPackageSet
// is applied by run_onchange_after_01-apply-tomei, i.e. *after* files):
//   - curl/ca-certificates/sudo/git: prerequisites for installing tomei itself;
//   - jq: used by dot_config/zed/modify_settings.json.tmpl during file apply.
// Those are provided by the base image (Dockerfile) / manual Phase 0 instead.
// (Runtime jq also comes from the aqua cliTools set.)
base: {
	apiVersion: "tomei.terassyi.net/v1beta1"
	kind:       "SystemPackageSet"
	metadata: name: "base"
	spec: {
		installerRef: "apt"
		packages: ["fish", "neovim", "file", "locales"]
	}
}

// common-build: general build toolchain shared across languages.
// mold is a fast linker (ELF/Linux only) usable by gcc/clang for C/C++/Rust.
commonBuild: {
	apiVersion: "tomei.terassyi.net/v1beta1"
	kind:       "SystemPackageSet"
	metadata: name: "common-build"
	spec: {
		installerRef: "apt"
		packages: ["build-essential", "pkg-config", "cmake", "mold"]
	}
}

// bpf-dev: eBPF compilation (clang/llvm), libbpf/CO-RE, bpftool, perf.
// bpftool is the standalone package (kernel-independent), preferred over the
// linux-tools-generic copy which is tied to the running kernel version.
// linux-tools-generic is kept for perf. libclang-dev provides libclang for
// bindgen (used by rust+aya's aya-tool to generate kernel bindings).
bpfDev: {
	apiVersion: "tomei.terassyi.net/v1beta1"
	kind:       "SystemPackageSet"
	metadata: name: "bpf-dev"
	spec: {
		installerRef: "apt"
		packages: [
			"clang",
			"llvm",
			"libbpf-dev",
			"libelf-dev",
			"libclang-dev",
			"bpftool",
			"linux-headers-generic",
			"linux-tools-generic",
		]
	}
}

// rust-dev: Rust-specific system deps (openssl crate).
rustDev: {
	apiVersion: "tomei.terassyi.net/v1beta1"
	kind:       "SystemPackageSet"
	metadata: name: "rust-dev"
	spec: {
		installerRef: "apt"
		packages: ["libssl-dev"]
	}
}

// lua-build: deps for the lua runtime's source build (readline).
luaBuild: {
	apiVersion: "tomei.terassyi.net/v1beta1"
	kind:       "SystemPackageSet"
	metadata: name: "lua-build"
	spec: {
		installerRef: "apt"
		packages: ["libreadline-dev"]
	}
}

// vm-runtime: system deps for the microVM / sandboxed runtime tools above.
// zstd provides the `zstd` binary that `tar -I zstd` execs when unpacking
// kata-containers' kata-static-*.tar.zst release archive; it is not part of a
// stock Ubuntu install (nor of the CI base image), so kata's install fails with
// "tar (grandchild): zstd: Cannot exec" without it.
// Ordering is implicit: tomei has no Tool -> SystemPackage dependency edge
// (dependsOn exists on Installer only), but system resources are applied by a
// separate engine that runs to completion before any user tool, and both this
// set and the privileged kata-containers Tool only run under
// `tomei apply --system` — so zstd is always in place first.
vmRuntime: {
	apiVersion: "tomei.terassyi.net/v1beta1"
	kind:       "SystemPackageSet"
	metadata: name: "vm-runtime"
	spec: {
		installerRef: "apt"
		packages: ["zstd"]
	}
}

// media: media tooling (ffmpeg) via apt.
media: {
	apiVersion: "tomei.terassyi.net/v1beta1"
	kind:       "SystemPackageSet"
	metadata: name: "media"
	spec: {
		installerRef: "apt"
		packages: ["ffmpeg"]
	}
}

// google-cloud-cli (gcloud): used by the Phase 2 age-key fetch from Secret
// Manager and for general GCP work. Not in Ubuntu's archive, so Google's APT
// repository is registered first. tomei fetches the armored signing key,
// verifies it against keyHash (fail-closed on mismatch), dearmors it in-process
// (tomei v0.2.2, #283 — no gnupg needed) into /usr/share/keyrings, writes a
// signed-by sources list, and runs `apt-get update`. The `gcloud` SystemPackage
// binds to this repo via repositoryRef, which is what orders the repo (and its
// apt-get update) before the install — tomei does NOT implicitly order repos
// ahead of package resources, so without repositoryRef they land in the same
// layer and the install races ahead, failing (google-cloud-cli not yet indexed).
// If Google rotates the key, re-derive keyHash and update it here:
//   curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sha256sum
gcloudRepo: {
	apiVersion: "tomei.terassyi.net/v1beta1"
	kind:       "SystemPackageRepository"
	metadata: name: "google-cloud-sdk"
	spec: {
		installerRef: "apt"
		apt: {
			url:     "https://packages.cloud.google.com/apt"
			keyUrl:  "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
			keyHash: "sha256:3ecc63922b7795eb23fdc449ff9396f9114cb3cf186d6f5b53ad4cc3ebfbb11f"
			suite:   "cloud-sdk"
			components: ["main"]
		}
	}
}

// gcloud: Google Cloud CLI via apt. repositoryRef binds this package to
// gcloudRepo so tomei orders the repo (and its apt-get update) before install.
gcloud: {
	apiVersion: "tomei.terassyi.net/v1beta1"
	kind:       "SystemPackage"
	metadata: name: "gcloud"
	spec: {
		installerRef:  "apt"
		repositoryRef: "google-cloud-sdk"
		package:       "google-cloud-cli"
	}
}

// docker (Docker Engine / CE): not in Ubuntu's archive, so Docker's official
// APT repository is registered first, mirroring the gcloudRepo flow above —
// tomei fetches the armored signing key, verifies it against keyHash
// (fail-closed on mismatch), dearmors it in-process (tomei v0.2.2, no gnupg)
// into /usr/share/keyrings, writes a signed-by sources list, and runs
// `apt-get update`. suite is the Ubuntu codename (resolute = 26.04, the target;
// see Dockerfile / CI ubuntu-26.04) — Docker keys its dists by codename, so this
// tracks the OS release rather than a version-independent suite like cloud-sdk.
// If Docker rotates the key, re-derive keyHash and update it here:
//   curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sha256sum
dockerRepo: {
	apiVersion: "tomei.terassyi.net/v1beta1"
	kind:       "SystemPackageRepository"
	metadata: name: "docker"
	spec: {
		installerRef: "apt"
		apt: {
			url:     "https://download.docker.com/linux/ubuntu"
			keyUrl:  "https://download.docker.com/linux/ubuntu/gpg"
			keyHash: "sha256:1500c1f56fa9e26b9b8f42452a553675796ade0807cdce11975eb98170b3a570"
			suite:   "resolute"
			components: ["stable"]
		}
	}
}

// docker-ce: the Docker Engine daemon. repositoryRef binds it to dockerRepo so
// tomei orders the repo (and its apt-get update) before install. docker-ce
// Depends on containerd.io and docker-ce-cli, which apt pulls in automatically;
// the buildx and compose plugins are separate packages (not Depends/Recommends)
// and so are declared explicitly below per Docker's official install steps.
dockerCe: {
	apiVersion: "tomei.terassyi.net/v1beta1"
	kind:       "SystemPackage"
	metadata: name: "docker-ce"
	spec: {
		installerRef:  "apt"
		repositoryRef: "docker"
		package:       "docker-ce"
	}
}

// docker-buildx-plugin: the `docker buildx` builder (BuildKit) subcommand.
dockerBuildx: {
	apiVersion: "tomei.terassyi.net/v1beta1"
	kind:       "SystemPackage"
	metadata: name: "docker-buildx-plugin"
	spec: {
		installerRef:  "apt"
		repositoryRef: "docker"
		package:       "docker-buildx-plugin"
	}
}

// docker-compose-plugin: the `docker compose` (Compose v2) subcommand.
dockerCompose: {
	apiVersion: "tomei.terassyi.net/v1beta1"
	kind:       "SystemPackage"
	metadata: name: "docker-compose-plugin"
	spec: {
		installerRef:  "apt"
		repositoryRef: "docker"
		package:       "docker-compose-plugin"
	}
}
